version: '2'
services:
  destroy:
    image: bitovi/bitops:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ENVIRONMENT=test
      - TF_STATE_BUCKET=pca-test-terraform
      - TERRAFORM_DESTROY=true
    volumes:
      - ./:/opt/bitops_deployment